name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      - name: Deploy to server and run restart script
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/deploy/${{ github.event.repository.name }} || \
            (mkdir -p ~/deploy && cd ~/deploy && git clone https://github.com/${{ github.repository }}.git)
            cd ~/deploy/${{ github.event.repository.name }}
            git pull origin main
            chmod +x restart.bash
            ./restart.bash
          EOF
